cc_binary(
    name="SizesCExecutable",

    # cf. https://docs.bazel.build/versions/main/user-manual.html#flag--conlyopt
    copts=["-Wall -lrt -flto -fuse-ld=gold"],

    srcs=["CPrimer/sizes.c"],
)